x0 = [0;0]; % initial point
xl = [-5;-5]; % lower bounds
xu = [5;5]; % upper bounds

% -4x1 + 10 x2 >= 0 represented as A x <= b
A = [4 -10];
b = 0;
Aeq = zeros(0,2);
beq = zeros(0,1);

% Parameters (in this case we do not use parameters)
p = [];

% Call fmincon
options = optimoptions('fmincon',...
    'SpecifyObjectiveGradient',true,...
    'SpecifyConstraintGradient',true,...
    'Display','none',...
    'Algorithm','interior-point');

[x,fval,exitflag,output]=fmincon(...
    @objfungradHimmelblau, x0, ...
    A, b, Aeq, beq, ...
    xl, xu, ...
    @confungradHimmelblau1, ...
    options, ...
    p);

x,fval,output
